### ISSUE TITLE
Unable to use HipChat backend with HipChat Server

### ISSUE THREAD

**Issue by amorphic** [gbin/err#348]
Err's HipChat backend forgoes the HipChat v2 API in favour of standard XMPP for basic chat functions as per https://github.com/gbin/err/commit/aef572ab790e0510d247499087039b8f8bf185fd.

However the HipChat backend still uses the HipChat v2 API for higher-level functionality such as creating and joining rooms. This happens in the `HipChatMUCRoom` class which in turn uses [hypchat](https://github.com/RidersDiscountCom/HypChat).

However the HipChat backend provides no interface to set hypchat's `endpoint` kwarg:

`self.hypchat = hypchat.HypChat(self.token)`

This prevents the HipChat backend from being used with HipChat Server. The pure XMPP backend can still be used with HipChat Server for basic functionality, but querying users, creating rooms etc doesn't really work.

It would be great if the HipChat backend allowed the hypchat `endpoint` to be specified so that the full range of the HipChat backend's functionality could be used with HipChat Server.

**Comment by zoni** [comment]
I've pushed a new branch, `hipchat_server`, which allows you to set an `endpoint` in your `BOT_IDENTITY` in `config.py`. Could you give this a try and see if it works for you? I don't have access to HipChat server to verify this for myself.

**Comment by amorphic** [comment]
:+1: Works a charm! Thanks for the quick turnaround! :smile:

Using this has exposed a separate issue when using self-signed certs with the HipChat backend. Even with `XMPP_CA_CERT_FILE` set, interactions with the API still fail. I think this is because `hypchat` doesn't expose Requests' `verify` kwarg, so the HipChat backend is unable to use a separate cert bundle file for the HipChat API interactions? I could be missing something however...

I've raised an Issue for HypChat to add support for the `verify` kwarg: https://github.com/RidersDiscountCom/HypChat/issues/37

In the meantime I can just export the `REQUESTS_CA_BUNDLE` env var as a workaround, so this isn't a showstopper.

**Comment by gbin** [comment]
@zoni, what still needs to be done here ?

**Comment by zoni** [comment]
I'd like to make it possible to adjust certificate validation on HipChat, and have it adjust the `hypchat` settings also so that you can easily connect Err to a server with a self-signed certificate or a server signed by a CA that isn't present in the system's CA store.

I've opened a more generic issue for this, though: #405
