### ISSUE TITLE
Unable to send message, has syntax or method changed ?

### ISSUE THREAD

**Issue by dmsimard** [gbin/err#411]
This might not be an issue so much as the syntax or the method for sending a message has changed since the last stable release... Hoping you can point me in the right direction.

I've been developing a plugin for errbot and before updating to the master branch, the following worked with the IRC backend to send a message to a chatroom:

    room = "#channel"
    message = "blah"
    self.send(room, msg, message_type='groupchat')

Now, I get the following stacktrace:

    Traceback (most recent call last):
      File "/usr/local/bin/bottle.py", line 862, in _handle
        return route.call(**args)
      File "/usr/local/bin/bottle.py", line 1732, in wrapper
        rv = callback(*a, **ka)
      File "/usr/local/lib/python2.7/dist-packages/errbot/core_plugins/wsview.py", line 92, in __call__
        response = self.func(data, **kwargs)
      File "/usr/local/bin/bot/plugins/livestatus/errbot-livestatus.py", line 128, in service
        self.monitoring_broadcast(message)
      File "/usr/local/bin/bot/plugins/livestatus/errbot-livestatus.py", line 214, in monitoring_broadcast
        self.send(room, msg, message_type='groupchat')
      File "/usr/local/lib/python2.7/dist-packages/errbot/botplugin.py", line 313, in send
        return self._bot.send(user, text, in_reply_to, message_type, groupchat_nick_reply)
      File "/usr/local/lib/python2.7/dist-packages/errbot/errBot.py", line 512, in send
        mess.to = user
      File "/usr/local/lib/python2.7/dist-packages/errbot/backends/base.py", line 92, in to
        % (to, to.__class__))
    Exception: `to` not an Identifier as it misses the "person" property. `to` : #channel (<type 'str'>)

Let me know..

Thanks for your quick fixes so far :)

**Comment by gbin** [comment]
The backward compatibility layer was not implemented yet on send for string identifiers.

I fixed it here: b4ff8b952a9d469eeb26c7c2761cfbfdd760e4ad

**Comment by dmsimard** [comment]
Thanks for taking a stab at this but it hasn't fixed the issue :(

New stack trace:

    Traceback (most recent call last):
      File "/usr/local/bin/bottle.py", line 862, in _handle
        return route.call(**args)
      File "/usr/local/bin/bottle.py", line 1732, in wrapper
        rv = callback(*a, **ka)
      File "/usr/local/lib/python2.7/dist-packages/errbot/core_plugins/wsview.py", line 92, in __call__
        response = self.func(data, **kwargs)
      File "/usr/local/bin/bot/plugins/livestatus/errbot-livestatus.py", line 128, in service
        self.monitoring_broadcast(message)
      File "/usr/local/bin/bot/plugins/livestatus/errbot-livestatus.py", line 214, in monitoring_broadcast
        self.send(room, msg, message_type='groupchat')
      File "/usr/local/lib/python2.7/dist-packages/errbot/botplugin.py", line 315, in send
        return self._bot.send(user, text, in_reply_to, message_type, groupchat_nick_reply)
      File "/usr/local/lib/python2.7/dist-packages/errbot/errBot.py", line 512, in send
        mess.to = user
      File "/usr/local/lib/python2.7/dist-packages/errbot/backends/base.py", line 92, in to
        % (to, to.__class__))
    Exception: `to` not an Identifier as it misses the "person" property. `to` : #channel (<type 'str'>)

**Comment by gbin** [comment]
Might be a snafu on str with py2.7
can you try to call self.build_identifier to see if it works ?
room = self.build_identifier('#channel')
self.send(room, 'blah', message_type='groupchat')

**Comment by dmsimard** [comment]
Ok so that worked. There's a blank message being sent after, though. So, like, two lines:

    <bot>: blah
    <bot>:

Will try and find why...

**Comment by dmsimard** [comment]
There wasn't any blank messages prior to upgrade but I checked anyway, I don't seem to have new lines or whitespace - added an rstrip() to msg anyway but that doesn't fix it. Don't have time to check further for the time being but will update you if I find anything.

**Comment by gbin** [comment]
thx, I'll look at the issue with py27 for the send method that doesn't detect a string properly

**Comment by dmsimard** [comment]
So, there isn't a blank line for every message but instead after the command is completed. Do you want me to open another issue ?

Here's what it looks like:

    <dmsimard> !help
    <bot> Available help:
    <bot> !help Backup:  Backup related commands. 
    <bot> !help ChatRoom: This is a basic implementation of a chatroom
    <bot> !help ErrbotLivestatus: An Err Nagios Livestatus Monitoring plugin
    <bot> !help Help: Core plugin of help related functions.
    <bot> !help Help: Core plugin for bot lifecycle and health related commands.
    <bot> !help Plugins: Commands to manage the plugins of the bot by chatting.
    <bot> !help Utils: Core Errbot utils commands.
    <bot> !help Webserver: This is a plugin for enabling webhooks and web interface to err
    <bot> 
    <dmsimard> !help Utils
    <bot> Available commands for Utils:
    <bot> !echo: A simple echo command. Useful for encoding tests etc ...
    <bot> !history: display the command history
    <bot> !log tail: Display a tail of the log of n lines or 40 by default
    <bot> !render test: Tests / showcases the markdown rendering on your current backend
    <bot> !whoami: A simple command echoing the details of your identifier. Useful to debug identity problems.
    <bot> 
    <dmsimard> !echo test
    <bot> test
    <bot>

**Comment by gbin** [comment]
please yeah, this is a  separate issue

**Comment by gbin** [comment]
so it was a py27 string detection bug fixed here 13a8e1d568e58c91df1702f86cac263207364c24
